refactor nvm and rustup install function

diff --git a/run_once_12-install-nvm.tmpl b/run_once_12-install-nvm.tmpl
--- a/run_once_12-install-nvm.tmpl
+++ b/run_once_12-install-nvm.tmpl
@@ -13,14 +13,14 @@ install_nvm() {
   # install nvm if not already installed
   if [[ -d "$NVM_DIR" ]] || command -v nvm >/dev/null 2>&1; then
     echo "nvm is already installed"
-  else
-    echo "nvm binary not found, installing..."
-    mkdir "$NVM_DIR" || exit
-    # install nvm
-    curl -sL "$1" -o "$2" || exit
-    bash "$2" || exit
-    rm "$2"
+    exit
   fi
+  echo "nvm binary not found, installing..."
+  mkdir "$NVM_DIR" || exit
+  # install nvm
+  curl -sL "$1" -o "$2" || exit
+  bash "$2" || exit
+  rm "$2"
 }
 
 install_nvm "$NVM_URL" "$NVM_INSTALLER"
diff --git a/run_once_13-install-rustup.tmpl b/run_once_13-install-rustup.tmpl
--- a/run_once_13-install-rustup.tmpl
+++ b/run_once_13-install-rustup.tmpl
@@ -11,13 +11,13 @@ install_rustup() {
   # install rustup if not already installed
   if command -v rustup >/dev/null 2>&1; then
     echo "rustup is already installed"
-  else
-    echo "rustup binary not found, installing..."
-    # install rustup
-    curl --proto '=https' --tlsv1.2 -sSf "$1" -o "$2" || exit
-    sh "$2" -y --no-modify-path || exit
-    rm "$2"
+    exit
   fi
+  echo "rustup binary not found, installing..."
+  # install rustup
+  curl --proto '=https' --tlsv1.2 -sSf "$1" -o "$2" || exit
+  sh "$2" -y --no-modify-path || exit
+  rm "$2"
 }
 
 install_rustup "$RUSTUP_URL" "$RUSTUP_INSTALLER"
